### ISSUE TITLE
Implement Milestone system

### ISSUE THREAD

**Issue by isuru89** [isuru89/oasis#3]
Users can play along milestones.
- [x] Milestone must have a finite amount of levels.
- [x] Milestones should be defined only using aggregation functions.
   - [x] Sum of points
   - [x] Sum of KPIs
   - [x] Count of events
- [x] Milestones does not have deadlines or end dates. They are playing forever.
- ~~When someone has achieved maximum level of a milestone, that milestone will be considered as completed for that user.~~
  - ~~Should be awarded an special badge and bonus points.~~
- [x] Milestone values can only be ever monotonically increasing.
  - [x] Penalty values or negative KPIs will be aggregating separately along with milestone
